### ISSUE TITLE
missing conf file etc/snowflakes-apache.conf in repo?

### ISSUE THREAD

**Issue by lidaof** [ENCODE-DCC/snovault#13]
Hi,

wondering is the file etc/snowflakes-apache.conf missing in the repo? if yes, can you please add it back? Thanks.

**Comment by hitz** [comment]
Oh interesting.   It's in /etc/encoded-apache.conf.  I didn't re-name it because it has a bunch of legacy redirects and I haven't tried actually DEPLOYING snovault.  It should be roughly the same (aside from a bunch of redirects you don't need)

You can try just renaming it and making a PR, there might be some futzing (s/encoded/snowflakes/?)
 to do too.  There is no s3 database for snowflakes set up so I don't think the deploy scripts will do anything useful as is.

**Comment by lidaof** [comment]
Thanks for fast reply Ben @hitz .
I am actually trying to setup snovault on a fresh installed Ubuntu (not on a cloud instance).
So I also need soft link the snowflakes folder to encoded under /srv?

Thanks again.

**Comment by hitz** [comment]
I think this is fixed in master now.
