### ISSUE TITLE
Issue with Buildout - GCP

### ISSUE THREAD

**Issue by lkalesinskas** [ENCODE-DCC/snovault#55]
Hi!
I'm currently working on setting up snovault for use on the Google Cloud Platform. I am using a clean Ubuntu 16.04 VM (largely following the instructions on the README.md with linuxbrew).
I am able to generate the bin/buildout script and run it and it makes it through most of the script, however, I run into a error towards the end of the buildout.

`Updating test.
Installing aws.
Installing aws-ip-ranges.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  137k  100  137k    0     0   450k      0 --:--:-- --:--:-- --:--:--  450k`

And then the buildout exits. From what I understand, this is an AWS package... Since we are using GCP, what adjustments would we have to make? Would you have any suggestions on how to fix this? 
Or is there a more optimal way  to install snovault on GCP than setting it up on an Ubuntu 16.04 VM manually? 
Thanks!

**Comment by hitz** [comment]
the aws-ip-ranges is just a file that maps AWS regions to IP address ranges.      The only place this is used is in types/file.py (in encoded) to lookup whether someone requesting a download is on aws; if it's not then it forces http instead of https connection.   We have to use this for the UCSC genome browser, among other things.

You won't need this file in GC at all.  If you do take code from encoded (probably has lots of useful stuff for MotrPac), then big parts of types/file.py will have to be rewritten to use gc api instead of boto.   You probably don't need the equivalent of google cloud IP mapping unless you need to filter incoming connects from inside/outside GC.

**Comment by lkalesinskas** [comment]
Thanks! 
I'm having a little trouble piecing together encoded and snovault - since it seems like they intersect a ton - is encoded the built-out version of snovault?
